import { hasDatabase } from "@/lib/db";
import * as db from "./db";
import * as mem from "./memory";

export const cleanupStaleUnclaimedAgent = hasDatabase() ? db.cleanupStaleUnclaimedAgent : mem.cleanupStaleUnclaimedAgent;
export const clearAgentAvatar = hasDatabase() ? db.clearAgentAvatar : mem.clearAgentAvatar;
export const consumeVettingChallenge = hasDatabase() ? db.consumeVettingChallenge : mem.consumeVettingChallenge;
export const countAgents = hasDatabase() ? db.countAgents : mem.countAgents;
export const createAgent = hasDatabase() ? db.createAgent : mem.createAgent;
export const createVettingChallenge = hasDatabase() ? db.createVettingChallenge : mem.createVettingChallenge;
export const deleteAgent = hasDatabase() ? db.deleteAgent : mem.deleteAgent;
export const followAgent = hasDatabase() ? db.followAgent : mem.followAgent;
export const getAgentByApiKey = hasDatabase() ? db.getAgentByApiKey : mem.getAgentByApiKey;
export const getAgentByClaimToken = hasDatabase() ? db.getAgentByClaimToken : mem.getAgentByClaimToken;
export const getAgentById = hasDatabase() ? db.getAgentById : mem.getAgentById;
export const getAgentByName = hasDatabase() ? db.getAgentByName : mem.getAgentByName;
export const getFollowingCount = hasDatabase() ? db.getFollowingCount : mem.getFollowingCount;
export const getRecentlyActiveAgents = hasDatabase() ? db.getRecentlyActiveAgents : mem.getRecentlyActiveAgents;
export const getVettingChallenge = hasDatabase() ? db.getVettingChallenge : mem.getVettingChallenge;
export const isFollowing = hasDatabase() ? db.isFollowing : mem.isFollowing;
export const listAgents = hasDatabase() ? db.listAgents : mem.listAgents;
export const markChallengeFetched = hasDatabase() ? db.markChallengeFetched : mem.markChallengeFetched;
export const setAgentAdmitted = hasDatabase() ? db.setAgentAdmitted : mem.setAgentAdmitted;
export const setAgentAvatar = hasDatabase() ? db.setAgentAvatar : mem.setAgentAvatar;
export const setAgentClaimed = hasDatabase() ? db.setAgentClaimed : mem.setAgentClaimed;
export const setAgentIdentityMd = hasDatabase() ? db.setAgentIdentityMd : mem.setAgentIdentityMd;
export const setAgentUnclaimed = hasDatabase() ? db.setAgentUnclaimed : mem.setAgentUnclaimed;
export const setAgentVetted = hasDatabase() ? db.setAgentVetted : mem.setAgentVetted;
export const touchAgentLastActiveAtIfStale = hasDatabase() ? db.touchAgentLastActiveAtIfStale : mem.touchAgentLastActiveAtIfStale;
export const unfollowAgent = hasDatabase() ? db.unfollowAgent : mem.unfollowAgent;
export const updateAgent = hasDatabase() ? db.updateAgent : mem.updateAgent;
