import { hasDatabase } from "@/lib/db";
import * as db from "./db";
import * as mem from "./memory";

export const addParticipant = hasDatabase() ? db.addParticipant : mem.addParticipant;
export const addSessionMessage = hasDatabase() ? db.addSessionMessage : mem.addSessionMessage;
export const claimProctorSession = hasDatabase() ? db.claimProctorSession : mem.claimProctorSession;
export const createCertificationJob = hasDatabase() ? db.createCertificationJob : mem.createCertificationJob;
export const createSession = hasDatabase() ? db.createSession : mem.createSession;
export const endSession = hasDatabase() ? db.endSession : mem.endSession;
export const getAgentEvaluationPoints = hasDatabase() ? db.getAgentEvaluationPoints : mem.getAgentEvaluationPoints;
export const getAllEvaluationResultsForAgent = hasDatabase() ? db.getAllEvaluationResultsForAgent : mem.getAllEvaluationResultsForAgent;
export const getCertificationJobById = hasDatabase() ? db.getCertificationJobById : mem.getCertificationJobById;
export const getCertificationJobByNonce = hasDatabase() ? db.getCertificationJobByNonce : mem.getCertificationJobByNonce;
export const getCertificationJobByRegistration = hasDatabase() ? db.getCertificationJobByRegistration : mem.getCertificationJobByRegistration;
export const getEvaluationRegistration = hasDatabase() ? db.getEvaluationRegistration : mem.getEvaluationRegistration;
export const getEvaluationRegistrationById = hasDatabase() ? db.getEvaluationRegistrationById : mem.getEvaluationRegistrationById;
export const getEvaluationResultById = hasDatabase() ? db.getEvaluationResultById : mem.getEvaluationResultById;
export const getEvaluationResultCount = hasDatabase() ? db.getEvaluationResultCount : mem.getEvaluationResultCount;
export const getEvaluationResults = hasDatabase() ? db.getEvaluationResults : mem.getEvaluationResults;
export const getEvaluationVersions = hasDatabase() ? db.getEvaluationVersions : mem.getEvaluationVersions;
export const getParticipants = hasDatabase() ? db.getParticipants : mem.getParticipants;
export const getPassedEvaluations = hasDatabase() ? db.getPassedEvaluations : mem.getPassedEvaluations;
export const getPendingCertificationJobs = hasDatabase() ? db.getPendingCertificationJobs : mem.getPendingCertificationJobs;
export const getPendingProctorRegistrations = hasDatabase() ? db.getPendingProctorRegistrations : mem.getPendingProctorRegistrations;
export const getSession = hasDatabase() ? db.getSession : mem.getSession;
export const getSessionByRegistrationId = hasDatabase() ? db.getSessionByRegistrationId : mem.getSessionByRegistrationId;
export const getSessionMessages = hasDatabase() ? db.getSessionMessages : mem.getSessionMessages;
export const hasEvaluationResultForRegistration = hasDatabase() ? db.hasEvaluationResultForRegistration : mem.hasEvaluationResultForRegistration;
export const hasPassedEvaluation = hasDatabase() ? db.hasPassedEvaluation : mem.hasPassedEvaluation;
export const listRecentEvaluationResults = hasDatabase() ? db.listRecentEvaluationResults : mem.listRecentEvaluationResults;
export const registerForEvaluation = hasDatabase() ? db.registerForEvaluation : mem.registerForEvaluation;
export const saveEvaluationResult = hasDatabase() ? db.saveEvaluationResult : mem.saveEvaluationResult;
export const startEvaluation = hasDatabase() ? db.startEvaluation : mem.startEvaluation;
export const updateAgentPointsFromEvaluations = hasDatabase() ? db.updateAgentPointsFromEvaluations : mem.updateAgentPointsFromEvaluations;
export const updateCertificationJob = hasDatabase() ? db.updateCertificationJob : mem.updateCertificationJob;
